var MigratoryDataClient={};
MigratoryDataClient.a=function(){return navigator.userAgent&&navigator.userAgent.indexOf("ANTGalio")!==-1?"Opera":navigator.userAgent&&navigator.userAgent.indexOf("Chrome")!==-1&&navigator.userAgent.indexOf("WebKit")!==-1?"WebKit Chrome":navigator.userAgent&&navigator.userAgent.indexOf("Android")!==-1?"WebKit Android":navigator.userAgent&&navigator.userAgent.indexOf("iPhone")!==-1?"WebKit iPhone":navigator.userAgent&&navigator.userAgent.indexOf("WebKit")!==-1?"WebKit":navigator.userAgent&&navigator.userAgent.indexOf("MSIE")!==
-1?"IE":navigator.userAgent&&navigator.userAgent.indexOf("Gecko")!==-1?"Gecko":navigator.userAgent&&navigator.userAgent.indexOf("Opera Mobi")!==-1?"Opera Mobile":navigator.userAgent&&navigator.userAgent.indexOf("Opera Mini")!==-1?"unknown":window.opera?"Opera":"unknown"};MigratoryDataClient.b=function(a){if(!document.body)throw"Error: The document doesn't have a body!";var b=true;if(this.c==="unknown"){b=false;if(a)if(this.d===null)throw"Error: Browser not supported!";else this.d(this.NOTIFY_UNSUPPORTED_BROWSER)}return b};
MigratoryDataClient.e=function(){if(document.readyState==="complete"||document.readyState==="interactive")this.f();else if(document.addEventListener){document.addEventListener("DOMContentLoaded",this.f,false);window.addEventListener("load",this.f,false)}else if(document.attachEvent){document.attachEvent("onreadystatechange",this.f);window.attachEvent("onload",this.f);var a=false;try{a=window.frameElement==null}catch(b){}document.documentElement.doScroll&&a&&this.g()}};
MigratoryDataClient.g=function(){if(!MigratoryDataClient.h){try{document.documentElement.doScroll("left")}catch(a){setTimeout(MigratoryDataClient.g,1);return}MigratoryDataClient.f()}};MigratoryDataClient.i=function(a){this.h?a():this.j.push(a)};MigratoryDataClient.f=function(){if(!MigratoryDataClient.h)if(document.body){MigratoryDataClient.h=true;for(var a=0;a<MigratoryDataClient.j.length;a++)MigratoryDataClient.j[a]();MigratoryDataClient.j=null}else setTimeout(MigratoryDataClient.f,13)};
MigratoryDataClient.k=function(a){var b=window.location.protocol,c=window.location.host,d=window.location.port;if(c.indexOf("localhost")===0)return{l:"localhost:80",m:a+"/"};if(d.length>0&&c.lastIndexOf(":")!==-1)c=c.substring(0,c.lastIndexOf(":"));var e=a.indexOf("//");if(e===-1)return null;var f=a.substring(0,e);if(b!==f)return null;a=a.substring(f.length+2);e=a.indexOf("/");if(e!==-1)a=a.substring(0,e);e=a.lastIndexOf(":");b="";if(e!==-1){b=a.substring(e+1);a=a.substring(0,e)}if(navigator.userAgent&&
navigator.userAgent.indexOf("ANTGalio")!==-1){e=80;if(f==="https:")e=443;if(b!==""&&b!==e&&d!==e)if(b!==d)return null}else if(b!==d)return null;if(a.length<4)return null;var g=-1;e=a.length-1;for(var h=c.length-1;e>=0&&h>=0;e--,h--)if(a.charAt(e)!==c.charAt(h)){g=e;break}d="";if(g===-1)if(e===-1&&h===-1){e=a.indexOf(".");d=a.substring(e+1)}else if(e===-1)if(c.charAt(h-1)===".")d=a;else{e=a.indexOf(".");if(e===-1)return null;d=a.substring(e+1)}else{if(h===-1)if(a.charAt(e-1)===".")d=c;else{e=c.indexOf(".");
if(e===-1)return null;d=c.substring(e+1)}}else{e=a.indexOf(".",g+1);if(e===-1)return null;d=a.substring(e+1)}if(d.length<4||d.indexOf(".")===-1)return null;d+=b.length>0?":"+b:"";a=f+"//"+a+(b.length>0?":"+b:"")+"/";if(this.n>=2){c=d.split(".");if(c.length>=this.n)d=c.slice(-1*this.n).join(".")}return{l:d,m:a}};MigratoryDataClient.o=function(a){return this.k(a)===null};
MigratoryDataClient.p=function(a,b){if(a.name)a=a.name;else{var c=a.toString();a=c.substring(c.indexOf("function")+8,c.indexOf("("));a=a.replace(/^\s+|\s+$/g,"");if(a.length===0)a="anonymous";if(a==="anonymous"&&typeof b==="object")for(var d=0;d<b.length;d++)for(var e in b[d])if(b[d].hasOwnProperty(e)&&typeof b[d][e]==="function")if(b[d][e].toString()===c)return e}return a};
MigratoryDataClient.q=function(a){if(a===null||a===undefined||typeof a==="number"||typeof a==="boolean")return a;else if(typeof a==="string")return'"'+a+'"';else if(typeof a==="function")return this.p(a,this)+"()";else if(a instanceof Array)return this.r(a);var b="{",c=0;for(var d in a){if(c>0)b+=", ";if(a.hasOwnProperty(d))b+=d+":"+this.q(a[d]);c++}b+="}";return b};
MigratoryDataClient.s=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=Math.random()*16|0;return(a=="x"?b:b&3|8).toString(16)})};
MigratoryDataClient.t=function(a,b){var c=MigratoryDataClient.u;if(a>0){if(a<=this.v)c=a*MigratoryDataClient.w-Math.floor(Math.random()*MigratoryDataClient.w);else if(MigratoryDataClient.x===MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF){a=a-this.v;c=Math.min(MigratoryDataClient.y*Math.pow(2,a)-Math.floor(Math.random()*MigratoryDataClient.y*a),MigratoryDataClient.z)}else c=MigratoryDataClient.y;if(b!==undefined&&c<MigratoryDataClient.u)c=MigratoryDataClient.u}return c};
MigratoryDataClient.a0=function(a,b){var c={};if(b.length>0)for(var d=0;d<b.length;d++)c[b[d]]=a[b[d]];else for(d in a)c[d]=a[d];return c};MigratoryDataClient.a1=function(a){for(var b=a.length,c=a.length-1;c>=0;c--){var d=a.charCodeAt(c);if(d>127&&d<=2047)b++;else if(d>2047&&d<=65535)b+=2}return b};
MigratoryDataClient.a2=function(a){a=String(a);for(var b,c,d,e="",f=0,g=a.length%3;f<a.length;){if((b=a.charCodeAt(f++))>255||(c=a.charCodeAt(f++))>255||(d=a.charCodeAt(f++))>255)throw new TypeError("Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.");b=b<<16|c<<8|d;e+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b>>18&63)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b>>12&63)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b>>6&63)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b&63)}return g?e.slice(0,g-3)+"===".substring(g):e};
MigratoryDataClient.a3=function(a){a=String(a).replace(/[\t\n\f\r ]+/g,"");if(!/^(?:[A-Za-z\d+\/]{4})*?(?:[A-Za-z\d+\/]{2}(?:==)?|[A-Za-z\d+\/]{3}=?)?$/.test(a))throw new TypeError("Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.");a+="==".slice(2-(a.length&3));for(var b,c="",d,e,f=0;f<a.length;){b="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++))<<18|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++))<<
12|(d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)))<<6|(e="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)));c+=d===64?String.fromCharCode(b>>16&255):e===64?String.fromCharCode(b>>16&255,b>>8&255):String.fromCharCode(b>>16&255,b>>8&255,b&255)}return c};MigratoryDataClient.a4=function(a){a=MigratoryDataClient.a3(a);return pako.inflateRaw(a,{to:"string"})};
MigratoryDataClient.a5=function(a){a=pako.deflateRaw(a,{to:"string"});return MigratoryDataClient.a2(a)};MigratoryDataClient.a6=function(a,b){for(var c=0;c<a.length;c++)if(a[c]===b)return c;return-1};MigratoryDataClient.a7=function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c]);return b};MigratoryDataClient.a8=function(a,b){for(var c=[],d=0;d<a.length;d++)this.a6(b,a[d])===-1&&c.push(a[d]);return c};
MigratoryDataClient.a9=function(a,b){for(var c=[],d=0;d<a.length;d++)this.a6(b,a[d])!==-1&&c.push(a[d]);return c};MigratoryDataClient.aa=function(a,b){for(var c=this.a7(a),d=0;d<b.length;d++)this.a6(a,b[d])===-1&&c.push(b[d]);return c};
MigratoryDataClient.ab=function(a,b,c,d,e,f){if(typeof b!=="object"||typeof b.length!=="number")throw"Error: "+a+" - invalid argument; expected a list";if(d!==null&&b.length<d)throw"Error: "+a+" - invalid argument; expected a list with a least "+d+" elements";if(c!==null)for(d=0;d<b.length;d++)if(typeof b[d]!==c)throw"Error: "+a+" - invalid argument; the element on the position '"+d+"' is not of type '"+c+"'";if(typeof e==="object"&&typeof e.test==="function")for(d=0;d<b.length;d++)if(!e.test(b[d]))throw"Error: "+
a+". "+f+"; the element on the position '"+d+"' is the cause of the error";};MigratoryDataClient.r=function(a){for(var b="[",c=0;c<a.length;c++){if(c>0)b+=", ";b+=this.q(a[c])}b+="]";return b};MigratoryDataClient.ac=function(a,b,c,d,e){this.ab(a,b,c,d,/^\/[^\/*]+\/([^\/*]+\/)*([^\/*]+|\*)$/,e)};
MigratoryDataClient.ad=function(a,b){if(a===this.ae.af)this.ag(b);else if(a===this.ae.ah)this.ai(b);else if(a===this.ae.aj)this.ak(b);else if(a===this.ae.al)this.am(b);else if(a!==this.ae.an)if(this.ao!==null)if(this.ao.ap===this.aq&&a===this.ae.aq)this.ar(b);else if(this.ao.ap===this.as&&a===this.ae.as)this.at(b);else this.ao.ap===this.au&&a===this.ae.au&&this.av(b)};
MigratoryDataClient.ar=function(a){var b=a[this.ae.ax];if(b!==undefined)this.ay(this.az,this.b0.b1[b]);else{if(this.b2!==this.b3){b=a[this.ae.b4];if(b===undefined){MigratoryDataClient.ay(this.az,"server subscribe response is missing the session id");return}this.b5=b;b=a[this.ae.b6];if(b!==undefined&&b!==null)if(b==1)MigratoryDataClient.b7=true;b=a[this.ae.b8];if(b!==undefined&&b!==null)MigratoryDataClient.b9=b;b=a[this.ae.ba];if(b!==undefined&&b!==null)MigratoryDataClient.bb=b*1E3*1.4;this.bc=a[this.ae.bd];
b=this.b2;this.b2=this.b3;this.bf=this.be=0;this.bg();this.bi(a[this.ae.bh]);var c=this.bj[this.bk].m;a=a[this.ae.bl];if(a!==undefined)c=a;if(b!==this.bm){this.bn.bo[this.bk]!==undefined&&this.bn.bo[this.bk].bp++;if(b===null||this.bq)this.br({type:this.NOTIFY_SERVER_UP,info:c})}else this.bn.bo[this.bk]!==undefined&&this.bn.bo[this.bk].bs++;this.bq=false}this.bt()}};MigratoryDataClient.at=function(a){a=a[this.ae.ax];a!==undefined?this.ay(this.az,this.b0.b1[a]):this.bt()};
MigratoryDataClient.av=function(a){a=a[this.ae.ax];a!==undefined?this.ay(this.az,this.b0.b1[a]):this.bt()};
MigratoryDataClient.ag=function(a){var b=this.ae.bu,c=this.ae.bv,d=this.ae.bw,e=this.ae.bx,f=this.ae.by,g=this.ae.bz,h=this.ae.c0;if(!(a[b]===undefined||a[c]===undefined))if(this.c1[a[b]]!==undefined){this.bi(a[this.ae.bh]);var j=false;if(a[g]!==undefined&&parseInt(a[g])===1)j=true;g=false;if(a[h]!==undefined&&parseInt(a[h])===1)g=true;h=this.MESSAGE_TYPE_UPDATE;if(a[e]!==undefined)h=a[e]==this.c2?this.MESSAGE_TYPE_SNAPSHOT:a[e]==this.c3?this.MESSAGE_TYPE_RECOVERED:a[e]==this.c4?this.MESSAGE_TYPE_HISTORICAL:
this.MESSAGE_TYPE_UPDATE;e="";if(a[d]!==undefined)e=a[d];c=a[c];if(g)if(window.pako)c=this.a4(c);else this.c5("Please include `pako.min.js` package to decompress compressed messages.");b={subject:a[b],content:c,closure:e,replySubject:a[f],retained:j,type:h,qos:MigratoryDataClient.QOS_STANDARD,seq:0,epoch:0,compressed:g};f=this.ae.c6;if(a[f]!==undefined){f=((new Date).getTime()&16777215)-a[f];if(f>-14400000)b.latency=f}if(MigratoryDataClient.b7==true&&this.c7(a)==true){f=parseInt(a[this.ae.c8]);a=
parseInt(a[this.ae.c9]);b.qos=MigratoryDataClient.QOS_GUARANTEED;b.seq=a;b.epoch=f;a=this.ca(b.subject,this.c1[b.subject],a,f);if(a!="in_order")if(a=="higher"){MigratoryDataClient.cb();return}}this.bn.bo[this.bk]!==undefined&&this.bn.bo[this.bk].cc++;this.br({message:b})}};MigratoryDataClient.c7=function(a){var b=this.ae.cd,c=true;if(a[b]!==undefined&&parseInt(a[b])==MigratoryDataClient.ce)c=false;return c};
MigratoryDataClient.ca=function(a,b,c,d){if(b.seqid!=d){b.seq=c;b.messagesReceivedUntilRecovery++;b.seqid=d;return"in_order"}if(c<=b.seq)return"lower";if(c==b.seq+1){if(b.currentSubscribeType==MigratoryDataClient.cf){b.currentSubscribeType=MigratoryDataClient.cg;a={type:this.NOTIFY_DATA_SYNC,info:a};this.br(a)}b.seq+=1;b.messagesReceivedUntilRecovery++;return"in_order"}if(b.messagesReceivedUntilRecovery>0)return"higher";b.seq=c;b.messagesReceivedUntilRecovery++;a={type:this.NOTIFY_DATA_RESYNC,info:a};
this.br(a);return"in_order"};MigratoryDataClient.ay=function(a,b){a=a+", "+b;b=this.bn.bo[this.bk].b1;if(b[a]===undefined)b[a]=1;else b[a]++;this.bf++;this.cb()};
MigratoryDataClient.ai=function(a){var b=this.ae.ch,c=this.ae.bu;if(!(a[b]===undefined||a[c]===undefined)){var d=true,e=this.NOTIFY_SUBSCRIBE_DENY;switch(a[b]){case "a":e=this.NOTIFY_SUBSCRIBE_ALLOW;d=false;break;case "d":b=a[this.ae.ax];if(b!==undefined){if(b==MigratoryDataClient.ci)e=this.NOTIFY_SUBSCRIBE_TIMEOUT}else e=this.NOTIFY_SUBSCRIBE_DENY;break}if(d===true){this.cj=this.a8(this.cj,[a[c]]);delete this.c1[a[c]]}this.br({type:e,info:a[c]})}};
MigratoryDataClient.br=function(a){this.ck.push(a);setTimeout(function(){var b=MigratoryDataClient.ck.shift();if("message"in b)MigratoryDataClient.cl.call(window,b.message);else MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,b)},0)};MigratoryDataClient.ak=function(a){a!==undefined&&a!==null&&Object.keys(a).length>0&&this.cm(a)};MigratoryDataClient.cm=function(a){var b=a[this.ae.bw];a=a[this.ae.ch];b!==undefined&&b!==null&&this.br({type:MigratoryDataClient.cn(a),info:b})};
MigratoryDataClient.am=function(a){var b=a[this.ae.bu];a=a[this.ae.bx];if(MigratoryDataClient.co==a)for(a=0;a<this.cj.length;a++){b=this.c1[this.cj[a]];var c=b.cacheRecoveryStatus;if(MigratoryDataClient.cp==c||MigratoryDataClient.cq==c||MigratoryDataClient.cr==c)b.nrOfConsecutiveRecovery=0;else{b.messagesReceivedUntilRecovery=0;b.seqid!=Number.MAX_SAFE_INTEGER&&b.nrOfConsecutiveRecovery++}}else{b=this.c1[b];if(b!==null)b.cacheRecoveryStatus=a}};
MigratoryDataClient.cn=function(a){if(a===undefined||a===null)return MigratoryDataClient.NOTIFY_PUBLISH_FAILED;switch(a){case "OK":return MigratoryDataClient.NOTIFY_PUBLISH_OK;case "DENY":return MigratoryDataClient.NOTIFY_PUBLISH_DENIED;default:return MigratoryDataClient.NOTIFY_PUBLISH_FAILED}};
MigratoryDataClient.bi=function(a){if(a!==undefined)if(this.cs==null)this.cs=a;else if(a!==this.cs){this.cs=a;for(a=0;a<this.cj.length;a++)this.c1[this.cj[a]]={seqid:Number.MAX_SAFE_INTEGER,seq:0,history:this.c1[this.cj[a]].history,nrOfConsecutiveRecovery:0,messagesReceivedUntilRecovery:0,cacheRecoveryStatus:MigratoryDataClient.cp,currentSubscribeType:MigratoryDataClient.cg}}};
MigratoryDataClient.ct=function(){this.bn.cu=(new Date).getTime();this.bn.bo[this.bk]!==undefined&&this.bn.bo[this.bk].cv++;this.cw!==null&&this.bg();this.ao!==null&&this.ao.ap===this.an&&this.bt();var a=(new Date).getTime();if(a-this.cx>=this.cy){this.cx=a;a={};a.ap=this.an;this.cz(a)}};MigratoryDataClient.bg=function(){this.cw!==null&&clearTimeout(this.cw);if(this.bb>0)this.cw=setTimeout(function(){MigratoryDataClient.bf++;MigratoryDataClient.cb()},this.bb)};
MigratoryDataClient.cb=function(){this.bn.bo[this.bk]!==undefined&&this.bn.bo[this.bk].d0++;if((new Date).getTime()-this.d1<18E4)this.d2++;else{this.d2=0;this.d1=(new Date).getTime()}if(this.d2>=MigratoryDataClient.d3){var a={type:this.NOTIFY_RECONNECT_RATE_EXCEEDED,info:""};MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,a);MigratoryDataClient.getSubjects();a=[];for(var b=0;b<MigratoryDataClient.bj.length;b++)a[b]=MigratoryDataClient.bj[b].d4+" "+MigratoryDataClient.bj[b].m;MigratoryDataClient.disconnect();
MigratoryDataClient.connect()}else{if(this.d5!==null){clearTimeout(this.d5);this.d5=null}this.d6();this.d7();this.d8();if(this.b2!==null)this.b2=this.d9;a=this.bj[this.bk].m;this.da.push(this.bj[this.bk]);this.bc=this.b5=this.bk=null;this.be++;if(this.cw!==null){clearTimeout(this.cw);this.cw=null}if(!this.bq&&(this.be===this.db||this.be===this.bj.length)){this.bq=true;a={type:this.NOTIFY_SERVER_DOWN,info:a};MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,a)}if(this.bj.length>0){a=
{};a.ap=this.aq;this.cz(a)}if(this.cj.length>0){a={};a.ap=this.as;a.cj=this.cj;this.cz(a)}}};
MigratoryDataClient.dc=function(){this.bn.bo[this.bk]!==undefined&&this.bn.bo[this.bk].d0++;if((new Date).getTime()-this.d1<18E4)this.d2++;else{this.d2=0;this.d1=(new Date).getTime()}if(this.d5!==null){clearTimeout(this.d5);this.d5=null}MigratoryDataClient.dd=null;this.d6();this.d7();this.d8();if(this.b2!==null)this.b2=this.d9;var a=this.bj[this.bk].m;this.da.push(this.bj[this.bk]);this.bc=this.b5=this.bk=null;this.be++;if(this.cw!==null){clearTimeout(this.cw);this.cw=null}if(!this.bq&&(this.be===
this.db||this.be===this.bj.length)){this.bq=true;a={type:this.NOTIFY_SERVER_DOWN,info:a};MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,a)}};MigratoryDataClient.de=function(){this.bt();if(this.bj.length>0){var a={};a.ap=this.aq;this.cz(a)}if(this.cj.length>0){a={};a.ap=this.as;a.cj=this.cj;this.cz(a)}};
MigratoryDataClient.df=function(){this.dg();var a=false,b=this.bj[this.bk].m,c=this.o(b);if(!MigratoryDataClient.dh){if(!this.di||!c)b=this.dj(b);if(!c&&!this.dk(b,this.bk))return}var d=c&&!this.dl?this.dm:null,e=null,f=null,g=this.dn,h=this.ae,j=null,i=null;if(MigratoryDataClient.dh){g=this.dp;d=this.dq}else if(this.c==="IE"&&c&&MigratoryDataClient.dr){g=this.ds;h=this.dt;d=this.du}if(this.b2!==this.b3){if(!MigratoryDataClient.dh)if(this.c==="IE"&&!c)if(this.dv){d=this.dw;g=this.dx}else{d=this.dy;
e="MigratoryDataClient0.dz";f=this.e0;g=this.e1;h=this.dt}else if(this.c==="IE"&&MigratoryDataClient.dr&&this.dv){a=true;d=this.dw;g=this.e2;h=this.dt}else{g=this.e3;if(this.c==="WebKit Android")g=this.e4;d=c&&!this.dl?this.dm:g;g=this.e5}j=navigator.userAgent;i=this.e6}c="";c+=this.e7(d,e,f,h,this.e8,a,j,i,this.e9);if("/"!==b.substring(b.length-1,b.length))b+="/";a=MigratoryDataClient.t(this.bf,this.aq);this.ea=setTimeout(function(){MigratoryDataClient.ea=null;MigratoryDataClient.ay(MigratoryDataClient.eb,
MigratoryDataClient.ao.ap)},a);g.call(this,b,this.bk,c)};
MigratoryDataClient.ec=function(){this.dg();var a=this.bj[this.bk].m,b=this.o(a);if(!MigratoryDataClient.dh){if(!this.di||!b)a=this.dj(a);if(!b&&!this.dk(a,this.bk))return}this.cj=this.aa(this.cj,this.ao.cj);var c=b&&!this.dl?this.dm:null,d=this.dn,e=this.ae;if(MigratoryDataClient.dh){d=this.ed;c=this.dq}else if(this.c==="IE"&&b&&MigratoryDataClient.dr){d=this.ds;e=this.dt;c=this.du}b="";for(var f=0;f<this.ao.cj.length;f++){var g=this.ao.cj[f];if(this.ao.ee!==undefined&&this.ao.ee===true)this.c1[g]=
{seqid:Number.MAX_SAFE_INTEGER,seq:0,history:this.ao.ef[g],nrOfConsecutiveRecovery:0,messagesReceivedUntilRecovery:0,cacheRecoveryStatus:MigratoryDataClient.cp,currentSubscribeType:MigratoryDataClient.cg};b+=this.eg(g,this.c1[g],c,this.b5,e,this.e9)}if("/"!==a.substring(a.length-1,a.length))a+="/";c=MigratoryDataClient.u;if(MigratoryDataClient.dh===false)c=MigratoryDataClient.t(this.bf,this.as);this.ea=setTimeout(function(){MigratoryDataClient.ea=null;MigratoryDataClient.ay(MigratoryDataClient.eb,
MigratoryDataClient.ao.ap)},c);d.call(this,a,this.bk,b)};
MigratoryDataClient.eh=function(){this.dg();var a=this.bj[this.bk].m,b=this.o(a);if(!MigratoryDataClient.dh){if(!this.di||!b)a=this.dj(a);if(!b&&!this.dk(a,this.bk))return}this.cj=this.a8(this.cj,this.ao.cj);if(this.b2!==this.b3){this.bt();for(b=0;b<this.ao.cj.length;b++)delete this.c1[this.ao.cj[b]]}else{var c=b&&!this.dl?this.dm:null,d=this.dn,e=this.ae;if(MigratoryDataClient.dh){c=this.dq;d=this.ed}else if(this.c==="IE"&&b&&MigratoryDataClient.dr&&this.dv){d=this.ds;e=this.dt;c=this.du;if("/"!==
a.substring(a.length-1,a.length))a+="/"}var f="";for(b=0;b<this.ao.cj.length;b++){var g=this.ao.cj[b];f+=this.ei(g,this.c1[g],c,this.b5,e,this.e9);delete this.c1[g]}this.ea=setTimeout(function(){MigratoryDataClient.ea=null;MigratoryDataClient.ay(MigratoryDataClient.eb,MigratoryDataClient.ao.ap)},this.u);d.call(this,a,this.bk,f)}};
MigratoryDataClient.ej=function(){this.dg();var a=this.bj[this.bk].m,b=this.o(a);if(!MigratoryDataClient.dh){if(!this.di||!b)a=this.dj(a);if(!b&&!this.dk(a,this.bk))return}if(this.b2!==this.b3)this.bt();else{var c=b&&!this.dl?this.dm:null,d=this.dn,e=this.ae,f=this.bc;if(MigratoryDataClient.dh){c=this.dq;d=this.ed;f=null}else if(this.c==="IE"&&b&&MigratoryDataClient.dr&&this.dv){d=this.ds;e=this.dt;c=this.du;if("/"!==a.substring(a.length-1,a.length))a+="/"}b=MigratoryDataClient.ek(this.b5,e,c,f,this.e9);
this.ea=setTimeout(function(){MigratoryDataClient.ea=null;MigratoryDataClient.ay(MigratoryDataClient.eb,MigratoryDataClient.ao.ap)},this.u);d.call(this,a,this.bk,b)}};
MigratoryDataClient.el=function(){this.dg();var a=this.bj[this.bk].m;if(MigratoryDataClient.dh)if(this.b2!==this.b3){a=this.ao.em.closure;if(a!==undefined&&a!==null){a={type:MigratoryDataClient.NOTIFY_PUBLISH_FAILED,info:a};this.br(a)}}else{var b=this.ed,c=this.en(this.ao.em,this.dq,this.b5,this.ae);if("/"!==a.substring(a.length-1,a.length))a+="/";if(this.a1(c)+12>this.b9){a=this.ao.em.closure;if(a!==undefined&&a!==null){a={type:MigratoryDataClient.NOTIFY_MESSAGE_SIZE_LIMIT_EXCEEDED,info:a};this.br(a)}}else b.call(this,
a,this.bk,c)}else{a=this.ao.em.closure;if(a!==undefined&&a!==null){a={type:MigratoryDataClient.NOTIFY_PUBLISH_FAILED,info:a};this.br(a)}}};MigratoryDataClient.bt=function(a){if(this.eo.length!==0)if(a!==undefined&&a!==null){if(this.eo[0].ap===a){this.eo.shift();this.d7();this.ep(false)}}else{this.eo.shift();this.d7();this.ep(false)}};MigratoryDataClient.cz=function(a){this.eo.push(a);this.eq(false)};
MigratoryDataClient.ep=function(a){this.eo.length!==0&&setTimeout(function(){MigratoryDataClient.eq(a)},0)};MigratoryDataClient.eq=function(a){if(this.er)if(this.b(true))if(!(!a&&(this.ao!==null||this.eo.length===0))){this.ao=this.eo[0];switch(this.ao.ap){case this.as:this.ec();break;case this.au:this.eh();break;case this.an:this.ej();break;case this.aq:this.df();break;case this.aw:this.el();this.bt();break;case this.es:this.dc();break;case this.et:this.de();break}}};
MigratoryDataClient.eu=function(){this.er=true;this.ep(false)};
MigratoryDataClient.d6=function(){for(;this.eo.length>0;){var a=this.eo[0];switch(a.ap){case this.as:var b=this.a8(a.cj,this.cj);if(b.length>0){this.cj=this.aa(this.cj,b);if(a.ee!==undefined&&a.ee===true)for(var c=0;c<b.length;c++)this.c1[b[c]]={seqid:Number.MAX_SAFE_INTEGER,seq:0,history:a.ef[b[c]],nrOfConsecutiveRecovery:0,messagesReceivedUntilRecovery:0,cacheRecoveryStatus:MigratoryDataClient.cp,currentSubscribeType:MigratoryDataClient.cg}}break;case this.au:b=this.a9(a.cj,this.cj);if(b.length>
0){this.cj=this.a8(this.cj,b);for(c=0;c<b.length;c++)delete this.c1[b[c]]}break;case this.aw:if(a.em.closure!==undefined&&a.em.closure!==null){a={type:this.NOTIFY_PUBLISH_FAILED,info:a.em.closure};MigratoryDataClient.d!==null&&MigratoryDataClient.d.call(window,a)}break}this.eo.shift()}};
MigratoryDataClient.d7=function(){this.ao=null;if(this.ea!==null){clearTimeout(this.ea);this.ea=null}if(this.ev!==null&&this.ev.readyState&&this.ev.readyState!==4){if(typeof XMLHttpRequest!=="undefined")this.ev.aborted=true;this.ev.abort()}this.ev!==null&&delete this.ev;this.ev=null};
MigratoryDataClient.d8=function(){if(this.ew!==null){var a="";if(this.ew.ex!==undefined)a=this.ew.ex;if(a!=="HTML5")if(a==="XDR_HTML5"){a=document.getElementById("MigratoryDataClient1");a!==null&&a.contentWindow.postMessage("disconnect","*")}else if(this.ew.getElementById){a=this.ew.getElementById("ey");if(a!==null){a.src="";this.ew.body.removeChild(a);delete a;a=null}delete this.ew;this.ew=null;CollectGarbage()}else{if(MigratoryDataClient.dh){this.ew.onmessage=function(){};this.ew.onopen=function(){};
this.ew.onclose=function(){};this.ew.close()}else{if(this.ew.ez!==undefined){clearTimeout(this.ew.ez);this.ew.ez=undefined}this.ew.readyState&&this.ew.readyState!==4&&this.ew.abort();a==="XDR_STREAM"&&this.ew.abort()}delete this.ew;this.ew=null}}};
MigratoryDataClient.f0=function(){this.d7();this.d8();this.b2=this.bk=null;this.cj=[];this.bc=this.b5=null;this.da=[];this.d2=this.be=0;this.d1=(new Date).getTime();this.bf=0;this.bq=false;this.eo=[];this.c1={};this.b7=false;if(this.cw!==null){clearTimeout(this.cw);this.cw=null}if(this.d5!==null){clearTimeout(this.d5);this.d5=null}};
MigratoryDataClient.f1=function(){if(this.o(this.bj[this.bk].m)&&!this.dl){if(this.ew!==null){this.ew.responseText="";this.ew.f2=0}}else{this.b2=this.bm;this.d8();this.bc=this.b5=null;if(this.bj.length>0){var a={};a.ap=this.aq;this.cz(a)}if(this.cj.length>0){a={};a.ap=this.as;a.cj=this.cj;this.cz(a)}}};MigratoryDataClient.dg=function(){if(this.bk===null)this.bk=this.f3()};
MigratoryDataClient.f3=function(){var a=this.a8(this.bj,this.da);if(a.length===0){this.da=[];a=this.bj}if(a.length===0)throw"Error: f3() No available servers!";for(var b=0,c=0;c<a.length;c++)b+=a[c].d4;var d=-1;if(b===0)d=Math.floor(a.length*Math.random());else{var e=Math.floor(b*Math.random());for(c=b=0;c<a.length;c++){b+=a[c].d4;if(b>e){d=c;break}}}return this.a6(this.bj,a[d])};
MigratoryDataClient.dj=function(a){var b=this.k(a);if(b===null||this.e0!==null&&b.l!==this.e0)throw"Error: Invalid common parent domain of the servers! Cause server is '"+a+"'.";if(this.e0===null){this.e0=b.l;if(b.l.indexOf(":")===-1)document.domain=b.l}return b.m};MigratoryDataClient.dk=function(a,b){var c="MigratoryDataClient2"+b;if(window.frames[c]===undefined||window.frames[c].f4===undefined){this.f5(a,b);return false}return true};
MigratoryDataClient.f5=function(a,b){b="MigratoryDataClient2"+b;var c=document.getElementById(b);if(!c){c=document.createElement("iframe");c.name=b;c.id=b;c.style.display="none";document.body.appendChild(c)}b=MigratoryDataClient.t(this.bf,this.as);this.ea=setTimeout(function(){MigratoryDataClient.ea=null;c.src="";c.parentNode.removeChild(c);MigratoryDataClient.ay(MigratoryDataClient.eb,"iframe")},b);if("/"!==a.substring(a.length-1,a.length))a+="/";c.src=a+"_"+this.f6(this.e0,"f4","MigratoryDataClient.f7")};
MigratoryDataClient.f7=function(){clearTimeout(this.ea);this.ea=null;this.ep(true)};MigratoryDataClient.f8=function(a){return this.dl?new XMLHttpRequest:this.f9(a)};
MigratoryDataClient.f9=function(a){if(a){if(this.fa)this.fa.responseText="";else this.fa={open:function(b,c){b=MigratoryDataClient.fb(c);MigratoryDataClient.fc.connect("0",b.host,b.port,"MigratoryDataClient.fd")},setRequestHeader:function(){},send:function(b){MigratoryDataClient.fc.write("0","POST / HTTP/1.1\r\nContent-Length: "+b.length+"\r\n\r\n"+b)},readyState:4,status:200,responseText:"",abort:function(){this.responseText="";MigratoryDataClient.fc.close("0")}};return this.fa}if(this.fe)this.fe.responseText=
"";else this.fe={open:function(b,c){b=MigratoryDataClient.fb(c);MigratoryDataClient.fc.connect("1",b.host,80,"MigratoryDataClient.ff")},setRequestHeader:function(){},send:function(b){MigratoryDataClient.fc.write("1","POST / HTTP/1.1\r\nContent-Length: "+b.length+"\r\n\r\n"+b)},readyState:4,status:200,responseText:"",abort:function(){this.responseText="";MigratoryDataClient.fc.close("1")}};return this.fe};
MigratoryDataClient.fb=function(a){var b,c;b=a.indexOf("https://")==0?"https://":"http://";a=a.substring(b.length);var d=a.indexOf("/");if(d!=-1){c=a.substring(0,d);a.substring(d)}else c=a;d=c.lastIndexOf(":");if(d!=-1){a=c.substring(d+1);c=c.substring(0,d)}else a=b=="https://"?"443":"80";return{host:c,port:a}};MigratoryDataClient.ff=function(a){if(this.ev){this.ev.responseText+=a;this.fg()}};MigratoryDataClient.fd=function(a){if(this.ew){this.ew.responseText+=a;this.fh()}};
MigratoryDataClient.fi=function(){this.b(false);var a=document.createElement("div");document.body.appendChild(a);var b=document.createElement("div");b.id="MigratoryDataClient3";a.appendChild(b);setTimeout(function(){var c="flash-transport.swf";if(typeof MigratoryDataClientFlashTransport==="string")c=MigratoryDataClientFlashTransport;swfobject.embedSWF(c,"MigratoryDataClient3","0","0","9",false,{readyCallback:"MigratoryDataClient.fj"},{allowFullScreen:false,allowScriptAccess:"always"},{id:"MigratoryDataClient4",
name:"MigratoryDataClient4"})},0)};MigratoryDataClient.fj=function(){MigratoryDataClient.fc=document.getElementById("MigratoryDataClient4");if(!MigratoryDataClient.fc)throw"Error: Could not get the reference of the flash-transport.swf!";MigratoryDataClient.eu()};
MigratoryDataClient.ds=function(a,b,c){b=document.getElementById("MigratoryDataClient5");if(b===null){b=document.createElement("iframe");b.id="MigratoryDataClient5";b.style.display="none";document.body.appendChild(b)}var d=(new Date).getTime();b.src=a+"_"+c+d};
MigratoryDataClient.e1=function(a,b,c){this.ew=new ActiveXObject("htmlfile");this.ew.open();MigratoryDataClient.e0.indexOf(":")===-1?this.ew.write("<html><head><script>document.domain='"+MigratoryDataClient.e0+"';<\/script></head><body></body></html>"):this.ew.write("<html><head></head><body></body></html>");this.ew.close();this.ew.parentWindow.MigratoryDataClient0=this;b=this.ew.createElement("iframe");b.id="ey";this.ew.body.appendChild(b);this.ew.fk=0;b.src=a+"_"+c};
MigratoryDataClient.dz=function(a){MigratoryDataClient.fl(a);MigratoryDataClient.ew.fk+=a.length;MigratoryDataClient.ew.fk>=MigratoryDataClient.fm&&MigratoryDataClient.ao===null&&MigratoryDataClient.b2!==MigratoryDataClient.bm&&MigratoryDataClient.f1()};
MigratoryDataClient.e2=function(a,b,c){this.ew={};this.ew.ex="XDR_HTML5";MigratoryDataClient.fk=0;b=document.getElementById("MigratoryDataClient1");if(b===null){b=document.createElement("iframe");b.id="MigratoryDataClient1";b.style.display="none";document.body.appendChild(b)}var d=(new Date).getTime();b.src=a+"_"+c+d};
MigratoryDataClient.fn=function(a){if(a.data.indexOf(MigratoryDataClient.ae.fo)!==-1){MigratoryDataClient.fl(a.data);MigratoryDataClient.fk+=a.data.length;MigratoryDataClient.fk>=MigratoryDataClient.fm&&MigratoryDataClient.ao===null&&MigratoryDataClient.b2!==MigratoryDataClient.bm&&MigratoryDataClient.f1()}};
MigratoryDataClient.dx=function(a,b,c){window.frames["MigratoryDataClient2"+b].f4("window.parent.MigratoryDataClient.ew = new XDomainRequest();");this.ew.f2=0;this.ew.ex="XDR_STREAM";this.ew.onload=function(){MigratoryDataClient.fp()};this.ew.onprogress=function(){MigratoryDataClient.fp()};this.ew.onerror=function(){};this.ew.ontimeout=function(){};try{this.ew.open("POST",a);this.ew.send(c)}catch(d){}};
MigratoryDataClient.fp=function(){var a=this.ew;if(a.responseText){for(var b=a.responseText.substring(a.f2),c=b.indexOf(this.ae.fq);c!==-1;){b=b.substring(0,c);this.fl(b);a.f2+=c+1;b=a.responseText.substring(a.f2);c=b.indexOf(this.ae.fq)}a.f2>=this.fm&&this.ao===null&&this.b2!==this.bm&&this.f1()}};
MigratoryDataClient.e5=function(a,b,c){var d=this.o(a);if(d)this.ew=this.f8(true);else window.frames["MigratoryDataClient2"+b].f4("window.parent.MigratoryDataClient.ew = new XMLHttpRequest();");this.ew.f2=0;this.ew.onreadystatechange=function(){MigratoryDataClient.fh()};this.ew.open("POST",a,true);d&&this.c.indexOf("WebKit")===0&&this.ew.setRequestHeader("Content-Type","text/plain");this.ew.send(c)};
MigratoryDataClient.fh=function(){var a=this.ew;if(!(a===null||a.readyState!==3&&a.readyState!==4||a.status!==200)){if(this.c.indexOf("Opera")!==-1){this.ew.ez!==undefined&&clearTimeout(this.ew.ez);this.ew.ez=setTimeout(function(){MigratoryDataClient.ew.ez=undefined;MigratoryDataClient.fh()},this.fr)}if(a.responseText){for(var b=a.responseText.substring(a.f2),c=b.indexOf(this.ae.fq);c!==-1;){b=b.substring(0,c);this.fl(b);a.f2+=c+1;b=a.responseText.substring(a.f2);c=b.indexOf(this.ae.fq)}a.f2>=this.fm&&
this.ao===null&&this.b2!==this.bm&&this.f1()}}};MigratoryDataClient.fs=function(){if(typeof XMLHttpRequest==="undefined"){try{return new ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(b){}try{return new ActiveXObject("Msxml2.XMLHTTP")}catch(c){}throw"Error: The browser does not support XMLHttpRequest!";}else return new XMLHttpRequest};
MigratoryDataClient.dn=function(a,b,c){var d=this.o(a);if(d)this.ev=this.f8(false);else window.frames["MigratoryDataClient2"+b].f4("window.parent.MigratoryDataClient.ev = ("+this.fs.toString()+")();");this.ev.onreadystatechange=function(){MigratoryDataClient.fg()};this.ev.open("POST",a,true);d&&this.c.indexOf("WebKit")===0&&this.ev.setRequestHeader("Content-Type","text/plain");if(this.c.indexOf("IE")===0){this.ev.setRequestHeader("Content-Type","text/plain");this.ev.setRequestHeader("Connection",
"close")}this.ev.send(c)};MigratoryDataClient.fg=function(){var a=this.ev;a===null||typeof XMLHttpRequest!=="undefined"&&typeof a.aborted!=="undefined"&&a.aborted!==null&&a.aborted==true||a===null||a.readyState!==4||a.status!==200||a.responseText&&this.fl(a.responseText)};
MigratoryDataClient.dp=function(a,b,c){var d;d=a.substring(0,a.indexOf("://"))==="http"?"ws://"+a.substring(a.indexOf("://")+3)+"WebSocketConnection":"wss://"+a.substring(a.indexOf("://")+3)+"WebSocketConnection-Secure";this.ew=MigratoryDataClient.ft(d);this.dd=MigratoryDataClient.s();this.ew.fu=this.dd;this.ew.onmessage=function(e){MigratoryDataClient.fv(e.data)};this.ew.onopen=function(){MigratoryDataClient.ed(a,b,c)};this.ew.onclose=function(){if(MigratoryDataClient.dd===this.fu){MigratoryDataClient.d7();
MigratoryDataClient.bf++;MigratoryDataClient.bt(MigratoryDataClient.aq);var e=MigratoryDataClient.t(MigratoryDataClient.bf);MigratoryDataClient.d5=setTimeout(function(){MigratoryDataClient.cb()},e)}}};MigratoryDataClient.ft=function(a){if(window.WebSocket)return new WebSocket(a);else if(window.MozWebSocket)return new MozWebSocket(a);return null};MigratoryDataClient.ed=function(a,b,c){this.ew!=null&&this.ew.readyState===1&&this.ew.send(c)};
MigratoryDataClient.fv=function(a){var b=MigratoryDataClient.ew;if(!(b===null||b.readyState!==1))if(a){b=a;for(var c=b.indexOf(MigratoryDataClient.ae.fq);c!==-1;){b=b.substring(0,c);MigratoryDataClient.fl(b);b=a.substring(c+1);c=b.indexOf(MigratoryDataClient.ae.fq)}}};MigratoryDataClient.fl=function(a){for(var b=0,c="\u0000",d={};;){var e=a.indexOf(this.ae.fo,b);if(e===-1)break;if(e-b>0){b=a.substring(b,e);c=b.charAt(0);d=this.fw(b);this.ad(c,d)}b=e+1}this.ct()};
MigratoryDataClient.fw=function(a){if(this.ae.fx[a.charAt(0)]!==undefined){for(var b=1,c={};;){if(b>=a.length)break;var d=a.charAt(b),e=a.indexOf(this.ae.fy,b+1);if(e===-1)return c;if(this.ae.fz[d]!==undefined){b++;var f="";switch(this.ae.g0[d]){case this.b0.g1:f=this.g2(this.ae,a.substring(b,e));break;case this.b0.g3:f=MigratoryDataClient.g4(this.ae,a.substring(b,e));break}b=c[d];if(b===undefined)c[d]=f;else if(c[d]instanceof Array)c[d][c[d].length]=f;else{c[d]=[];c[d][0]=b;c[d][1]=f}}b=e+1}return c}};
MigratoryDataClient.f6=function(a,b,c){var d="";d+=this.dt.g5;d+=this.dt.g6;d+=this.g7(this.dt,a);d+=this.dt.fy;d+=this.dt.g8;d+=this.g7(this.dt,b);d+=this.dt.fy;d+=this.dt.g9;d+=this.g7(this.dt,c);d+=this.dt.fy;d+=this.dt.fo;return d};
MigratoryDataClient.e7=function(a,b,c,d,e,f,g,h,j){var i="";i+=f?d.ga:d.aq;if(a!==null){i+=d.gb;i+=this.gc(d,a);i+=d.fy;if(this.c.indexOf("Opera")!==-1){i+=d.gd;i+=this.gc(d,1);i+=d.fy}}if(b!==null){i+=d.g9;i+=this.g7(d,b);i+=d.fy}if(c!==null){i+=d.g6;i+=this.g7(d,c);i+=d.fy}if(e!==null){i+=d.ge;i+=this.g7(d,e);i+=d.fy}if(g!==null){i+=d.bl;i+=this.g7(d,g);i+=d.fy}if(h!==null){i+=d.gf;i+=this.gc(d,h);i+=d.fy}i+=d.gg;i+=this.gc(d,j);i+=d.fy;i+=d.fo;return i};
MigratoryDataClient.eg=function(a,b,c,d,e,f){var g="";g+=e.as;g+=e.bu;g+=this.g7(e,a);g+=e.fy;if(c!==null){g+=e.gb;g+=this.gc(e,c);g+=e.fy;if(this.c.indexOf("Opera")!==-1){g+=e.gd;g+=this.gc(e,1);g+=e.fy}}if(d!==null){g+=e.b4;g+=this.gc(e,d);g+=e.fy}a=this.gh(b);if(a==MigratoryDataClient.gi){g+=e.gj;g+=this.gc(e,b.history);g+=e.fy}else if(a==MigratoryDataClient.cf){g+=e.c8;g+=this.gc(e,b.seqid);g+=e.fy;g+=e.c9;g+=this.gc(e,b.seq+1);g+=e.fy}g+=e.gg;g+=this.gc(e,f);g+=e.fy;g+=e.fo;return g};
MigratoryDataClient.gh=function(a){var b=MigratoryDataClient.cg;if(a.seqid!=Number.MAX_SAFE_INTEGER)if(a.nrOfConsecutiveRecovery>=MigratoryDataClient.gk){if(a.history>0)b=MigratoryDataClient.gi}else b=MigratoryDataClient.cf;else if(a.history>0)b=MigratoryDataClient.gi;if(b==MigratoryDataClient.cg||b==MigratoryDataClient.gi){a.cacheRecoveryStatus=MigratoryDataClient.cp;a.nrOfConsecutiveRecovery=0}return a.currentSubscribeType=b};
MigratoryDataClient.ei=function(a,b,c,d,e,f){b="";b+=e.au;b+=e.bu;b+=this.g7(e,a);b+=e.fy;if(d!==null){b+=e.b4;b+=this.gc(e,d);b+=e.fy}if(c!==null){b+=e.gb;b+=this.gc(e,c);b+=e.fy}b+=e.gg;b+=this.gc(e,f);b+=e.fy;b+=e.fo;return b};MigratoryDataClient.ek=function(a,b,c,d,e){var f="";f+=b.an;f+=b.b4;f+=this.gc(b,a);f+=b.fy;if(c!==null){f+=b.gb;f+=this.gc(b,c);f+=b.fy}if(d!==null){f+=b.bd;f+=this.gc(b,d);f+=b.fy}f+=b.gg;f+=this.gc(b,e);f+=b.fy;f+=b.fo;return f};
MigratoryDataClient.en=function(a,b,c,d){var e="";e+=d.aw;e+=d.bu;e+=this.g7(d,a.subject);e+=d.fy;var f=a.content;if(a.compressed)if(window.pako){var g=this.a5(f);if(g.length<f.length)f=g;else a.compressed=false}else{this.c5("Please include `pako.min.js` package to use compression feature.");a.compressed=false}e+=d.bv;e+=this.g7(d,f);e+=d.fy;if(a.closure!==undefined&&a.closure!==null){e+=d.bw;e+=this.g7(d,a.closure);e+=d.fy}if(a.replySubject!==undefined&&a.replySubject!==null){e+=d.by;e+=this.g7(d,
a.replySubject);e+=d.fy}if(a.qos!==undefined&&a.qos!==null){if(a.qos==MigratoryDataClient.QOS_GUARANTEED){e+=d.cd;e+=this.gc(d,MigratoryDataClient.gl)}else{e+=d.cd;e+=this.gc(d,MigratoryDataClient.ce)}e+=d.fy}if(a.retained!==undefined&&a.retained!==null){if(a.retained===true){e+=d.bz;e+=this.gc(d,1)}else{e+=d.bz;e+=this.gc(d,0)}e+=d.fy}if(a.compressed!==undefined&&a.compressed!==null)if(a.compressed===true){e+=d.c0;e+=this.gc(d,1);e+=d.fy}if(b!==null){e+=d.gb;e+=this.gc(d,b);e+=d.fy;if(this.c.indexOf("Opera")!==
-1){e+=d.gd;e+=this.gc(d,1);e+=d.fy}}if(c!==null){e+=d.b4;e+=this.gc(d,c);e+=d.fy}e+=d.fo;return e};MigratoryDataClient.dt={};MigratoryDataClient.dt.fo="!";MigratoryDataClient.dt.fq="z";MigratoryDataClient.dt.fy="$";MigratoryDataClient.dt.gm="~";MigratoryDataClient.dt.gn=" ";MigratoryDataClient.dt.go='"';MigratoryDataClient.dt.gp="#";MigratoryDataClient.dt.gq="%";MigratoryDataClient.dt.gr="'";MigratoryDataClient.dt.gs="/";MigratoryDataClient.dt.gt="<";MigratoryDataClient.dt.gu=">";
MigratoryDataClient.dt.gv="[";MigratoryDataClient.dt.gw="\\";MigratoryDataClient.dt.gx="]";MigratoryDataClient.dt.gy="^";MigratoryDataClient.dt.gz="`";MigratoryDataClient.dt.h0="{";MigratoryDataClient.dt.h1="|";MigratoryDataClient.dt.h2="}";MigratoryDataClient.dt.h3="";MigratoryDataClient.dt.as="&";MigratoryDataClient.dt.au="(";MigratoryDataClient.dt.af=")";MigratoryDataClient.dt.an="*";MigratoryDataClient.dt.g5="+";MigratoryDataClient.dt.h4=",";MigratoryDataClient.dt.ah="0";
MigratoryDataClient.dt.ga="2";MigratoryDataClient.dt.aw="5";MigratoryDataClient.dt.aj="8";MigratoryDataClient.dt.al=".";MigratoryDataClient.dt.h5="B";MigratoryDataClient.dt.aq="D";MigratoryDataClient.dt.bu="&";MigratoryDataClient.dt.bv="(";MigratoryDataClient.dt.c9=")";MigratoryDataClient.dt.c8="*";MigratoryDataClient.dt.gb="+";MigratoryDataClient.dt.b4=",";MigratoryDataClient.dt.g6="-";MigratoryDataClient.dt.g9=".";MigratoryDataClient.dt.g8="?";MigratoryDataClient.dt.ax="0";
MigratoryDataClient.dt.h6="1";MigratoryDataClient.dt.c6="2";MigratoryDataClient.dt.gd="3";MigratoryDataClient.dt.bw="4";MigratoryDataClient.dt.b6="5";MigratoryDataClient.dt.ge="7";MigratoryDataClient.dt.ch="8";MigratoryDataClient.dt.bd="9";MigratoryDataClient.dt.bz="A";MigratoryDataClient.dt.cd="B";MigratoryDataClient.dt.bx="J";MigratoryDataClient.dt.bl="K";MigratoryDataClient.dt.gf="L";MigratoryDataClient.dt.ba="M";MigratoryDataClient.dt.gj="N";MigratoryDataClient.dt.by="R";
MigratoryDataClient.dt.gg="S";MigratoryDataClient.dt.bh="[";MigratoryDataClient.dt.b8="G";MigratoryDataClient.dt.c0="H";MigratoryDataClient.dt.h7={};
(function(a){var b=a.h7;b["\u0000"]="y";for(var c=1;c<8;c++)b[String.fromCharCode(c)]=String.fromCharCode(c+39);b["\u0008"]="x";for(c=9;c<21;c++)b[String.fromCharCode(c)]=String.fromCharCode(c+39);b["\u0015"]="=";for(c=22;c<32;c++)b[String.fromCharCode(c)]=String.fromCharCode(c+41);b[a.fo]="I";b[a.fq]="w";b[a.fy]="J";b[a.gm]="K";b[a.gn]="L";b[a.go]="M";b[a.gp]="N";b[a.gq]="O";b[a.gr]="P";b[a.gs]="_";b[a.gt]="Q";b[a.gu]="R";b[a.gv]="S";b[a.gw]="T";b[a.gx]="U";b[a.gy]="V";b[a.gz]="W";b[a.h0]="X";b[a.h1]=
"Y";b[a.h2]="Z";b[a.h3]="v"})(MigratoryDataClient.dt);MigratoryDataClient.dt.h8={};(function(a){for(var b in a.h7)if(a.h7.hasOwnProperty(b))a.h8[a.h7[b]]=b})(MigratoryDataClient.dt);MigratoryDataClient.ae={};MigratoryDataClient.ae.fo="";MigratoryDataClient.ae.fq="\u0019";MigratoryDataClient.ae.fy="\u001e";MigratoryDataClient.ae.gm="\u001f";MigratoryDataClient.ae.h9="\u0000";MigratoryDataClient.ae.ha="\n";MigratoryDataClient.ae.hb="\r";MigratoryDataClient.ae.go='"';MigratoryDataClient.ae.gw="\\";
MigratoryDataClient.ae.as="\u0001";MigratoryDataClient.ae.au="\u0002";MigratoryDataClient.ae.af="\u0003";MigratoryDataClient.ae.an="\u0004";MigratoryDataClient.ae.g5="\u0005";MigratoryDataClient.ae.h4="\u0006";MigratoryDataClient.ae.ah="\t";MigratoryDataClient.ae.ga="\u000c";MigratoryDataClient.ae.aw="\u0010";MigratoryDataClient.ae.aj="\u0013";MigratoryDataClient.ae.al="\u0008";MigratoryDataClient.ae.h5="\u0017";MigratoryDataClient.ae.aq="\u001a";MigratoryDataClient.ae.bu="\u0001";
MigratoryDataClient.ae.bv="\u0002";MigratoryDataClient.ae.c9="\u0003";MigratoryDataClient.ae.c8="\u0004";MigratoryDataClient.ae.gb="\u0005";MigratoryDataClient.ae.b4="\u0006";MigratoryDataClient.ae.g6="\u0007";MigratoryDataClient.ae.g9="\u0008";MigratoryDataClient.ae.g8="\t";MigratoryDataClient.ae.ax="\u000b";MigratoryDataClient.ae.h6="\u000c";MigratoryDataClient.ae.c6="\u000e";MigratoryDataClient.ae.gd="\u000f";MigratoryDataClient.ae.bw="\u0010";MigratoryDataClient.ae.b6="\u0011";
MigratoryDataClient.ae.ge="\u0013";MigratoryDataClient.ae.ch="\u0014";MigratoryDataClient.ae.bd="\u0015";MigratoryDataClient.ae.bz="\u0017";MigratoryDataClient.ae.cd="\u0018";MigratoryDataClient.ae.bl="#";MigratoryDataClient.ae.gf="$";MigratoryDataClient.ae.ba="%";MigratoryDataClient.ae.bx="'";MigratoryDataClient.ae.gj="(";MigratoryDataClient.ae.by=",";MigratoryDataClient.ae.gg="-";MigratoryDataClient.ae.bh="0";MigratoryDataClient.ae.b8="\u001d";MigratoryDataClient.ae.c0="&";
MigratoryDataClient.ae.h7={};(function(a){var b=a.h7;b[a.fo]="\u0001";b[a.fy]="\u0002";b[a.gm]="\u0003";b[a.h9]="\u0004";b[a.ha]="\u0005";b[a.hb]="\u0006";b[a.go]="\u0007";b[a.gw]="\u0008";b[MigratoryDataClient.dt.fo]="\t";b[a.fq]="\u000b"})(MigratoryDataClient.ae);MigratoryDataClient.ae.h8={};(function(a){for(var b in a.h7)if(a.h7.hasOwnProperty(b))a.h8[a.h7[b]]=b})(MigratoryDataClient.ae);MigratoryDataClient.ae.fx={};
(function(a){a.fx[a.as]=true;a.fx[a.au]=true;a.fx[a.af]=true;a.fx[a.an]=true;a.fx[a.g5]=true;a.fx[a.h4]=true;a.fx[a.ah]=true;a.fx[a.ga]=true;a.fx[a.aw]=true;a.fx[a.aj]=true;a.fx[a.al]=true;a.fx[a.h5]=true;a.fx[a.aq]=true})(MigratoryDataClient.ae);MigratoryDataClient.ae.fz={};
(function(a){a.fz[a.bu]=true;a.fz[a.bv]=true;a.fz[a.c9]=true;a.fz[a.c8]=true;a.fz[a.gb]=true;a.fz[a.b4]=true;a.fz[a.g6]=true;a.fz[a.g9]=true;a.fz[a.g8]=true;a.fz[a.ax]=true;a.fz[a.h6]=true;a.fz[a.c6]=true;a.fz[a.gd]=true;a.fz[a.b6]=true;a.fz[a.ge]=true;a.fz[a.ch]=true;a.fz[a.bd]=true;a.fz[a.bx]=true;a.fz[a.bl]=true;a.fz[a.gf]=true;a.fz[a.bw]=true;a.fz[a.gj]=true;a.fz[a.ba]=true;a.fz[a.by]=true;a.fz[a.gg]=true;a.fz[a.bh]=true;a.fz[a.bz]=true;a.fz[a.cd]=true;a.fz[a.b8]=true;a.fz[a.c0]=true})(MigratoryDataClient.ae);
MigratoryDataClient.b0={};MigratoryDataClient.b0.hc=1;MigratoryDataClient.b0.hd=2;MigratoryDataClient.b0.g3=3;MigratoryDataClient.b0.g1=4;MigratoryDataClient.b0.he={};(function(a){var b=a.he;b.bu=a.g3;b.bv=a.g3;b.c9=a.g1;b.c8=a.g1;b.gb=a.g1;b.b4=a.g1;b.g6=a.g3;b.g9=a.g3;b.g8=a.g3;b.ax=a.g1;b.h6=a.g3;b.c6=a.g1;b.gd=a.g1;b.ge=a.g3;b.ch=a.g3;b.bd=a.g1;b.bx=a.g3;b.bl=a.g3;b.gf=a.g1;b.bw=a.g3;b.b6=a.g1;b.ba=a.g1;b.by=a.g3;b.gg=a.g1;b.bh=a.g3;b.bz=a.g1;b.cd=a.g1;b.b8=a.g1;b.c0=a.g1})(MigratoryDataClient.b0);
MigratoryDataClient.ae.g0={};MigratoryDataClient.dt.g0={};(function(){for(var a in MigratoryDataClient.b0.he)if(MigratoryDataClient.b0.he.hasOwnProperty(a)){MigratoryDataClient.ae.g0[MigratoryDataClient.ae[a]]=MigratoryDataClient.b0.he[a];MigratoryDataClient.dt.g0[MigratoryDataClient.dt[a]]=MigratoryDataClient.b0.he[a]}})();MigratoryDataClient.b0.b1={};MigratoryDataClient.b0.b1[0]="UNKNOWN_SESSION_ID";
MigratoryDataClient.g7=function(a,b){for(var c="",d=0;d<b.length;d++){var e=a.h7[b.charAt(d)];if(e!==undefined){c+=a.gm;c+=e}else c+=b.charAt(d)}return c};MigratoryDataClient.g4=function(a,b){for(var c="",d=0;d<b.length;d++){var e=b.charAt(d);if(e===a.gm){if(d+1>=b.length||a.h8[b.charAt(d+1)]===undefined)throw"Error: g4() Illegal argument '"+b+"'!";e=a.h8[b.charAt(d+1)];d++}c+=e}return c};
MigratoryDataClient.gc=function(a,b){if((b&4294967168)===0){var c=String.fromCharCode(b),d=a.h7[c];return d===undefined?c:a.gm+d}var e;e=(b&4278190080)!==0?24:(b&16711680)!==0?16:8;c=[];for(d=0;d<10;d++)c.push(0);for(var f=0,g=0;e>=0;){var h=b>>e&255;g++;c[f]|=h>>g;d=a.h7[String.fromCharCode(c[f])];if(d!==undefined){c[f]=a.gm.charCodeAt(0);c[f+1]=d.charCodeAt(0);f++}f++;c[f]|=h<<7-g&127;e-=8}d=a.h7[String.fromCharCode(c[f])];if(d!==undefined){c[f]=a.gm.charCodeAt(0);c[f+1]=d.charCodeAt(0);f++}f++;
a="";for(d=0;d<f;d++)a+=String.fromCharCode(c[d]);return a};
MigratoryDataClient.g2=function(a,b){var c="Error: g2() Illegal argument '"+b+"'!",d=0,e=-1,f=0,g,h=b.length,j=0;if(h===1)return b.charCodeAt(0);else if(h===2&&b.charAt(0)===a.gm){g=a.h8[b.charAt(1)];if(g!==undefined)return g.charCodeAt(0);else throw c;}for(;h>0;h--){g=b.charAt(j);j++;if(g===a.gm){if(h-1<0)throw c;h--;g=b.charAt(j);j++;g=a.h8[g];if(g===undefined)throw c;}else g=g;if(e>0){f|=g.charCodeAt(0)>>e;d=d<<8|f;f=g.charCodeAt(0)<<8-e}else f=g.charCodeAt(0)<<-e;e=(e+7)%8}return d};
MigratoryDataClient.NOTIFY_UNSUPPORTED_BROWSER="NOTIFY_UNSUPPORTED_BROWSER";MigratoryDataClient.NOTIFY_SERVER_DOWN="NOTIFY_SERVER_DOWN";MigratoryDataClient.NOTIFY_SERVER_UP="NOTIFY_SERVER_UP";MigratoryDataClient.NOTIFY_DATA_RESYNC="NOTIFY_DATA_RESYNC";MigratoryDataClient.NOTIFY_DATA_SYNC="NOTIFY_DATA_SYNC";MigratoryDataClient.NOTIFY_PUBLISH_OK="NOTIFY_PUBLISH_OK";MigratoryDataClient.NOTIFY_PUBLISH_FAILED="NOTIFY_PUBLISH_FAILED";MigratoryDataClient.NOTIFY_PUBLISH_DENIED="NOTIFY_PUBLISH_DENIED";
MigratoryDataClient.NOTIFY_MESSAGE_SIZE_LIMIT_EXCEEDED="NOTIFY_MESSAGE_SIZE_LIMIT_EXCEEDED";MigratoryDataClient.NOTIFY_SUBSCRIBE_ALLOW="NOTIFY_SUBSCRIBE_ALLOW";MigratoryDataClient.NOTIFY_SUBSCRIBE_DENY="NOTIFY_SUBSCRIBE_DENY";MigratoryDataClient.NOTIFY_SUBSCRIBE_TIMEOUT="NOTIFY_SUBSCRIBE_TIMEOUT";MigratoryDataClient.NOTIFY_RECONNECT_RATE_EXCEEDED="NOTIFY_RECONNECT_RATE_EXCEEDED";MigratoryDataClient.CONSTANT_WINDOW_BACKOFF="CONSTANT_WINDOW_BACKOFF";
MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF="TRUNCATED_EXPONENTIAL_BACKOFF";MigratoryDataClient.QOS_STANDARD="QOS_STANDARD";MigratoryDataClient.QOS_GUARANTEED="QOS_GUARANTEED";MigratoryDataClient.MESSAGE_TYPE_SNAPSHOT="MESSAGE_TYPE_SNAPSHOT";MigratoryDataClient.MESSAGE_TYPE_UPDATE="MESSAGE_TYPE_UPDATE";MigratoryDataClient.MESSAGE_TYPE_RECOVERED="MESSAGE_TYPE_RECOVERED";MigratoryDataClient.MESSAGE_TYPE_HISTORICAL="MESSAGE_TYPE_HISTORICAL";
MigratoryDataClient.connect=function(){if(this.hf)throw"Error: connect() - already connected";if(this.bj===undefined||this.bj===null||this.bj.length==0)throw"Error: connect() - no server to connect to; use setServers() to specify one or more servers";if(this.cl===undefined||this.cl===null)throw"Error: connect() - no message handler; use setMessageHandler() to specify a message handler";if(this.d===undefined||this.d===null)throw"Error: connect() - no status handler; use setStatusHandler() to specify a status handler";
this.hf=true;var a={};a.ap=this.aq;this.cz(a);if(this.hg.length>0){a={};a.ap=this.as;a.cj=this.a7(this.hg);a.ef=this.a0(this.hh,[]);a.ee=true;this.cz(a)}};MigratoryDataClient.notifyAfterFailedConnectionAttempts=function(a){if(this.hf)throw"Error: notifyAfterFailedConnectionAttempts() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: notifyAfterFailedConnectionAttempts() - invalid argument; expected a positive integer";this.db=a};
MigratoryDataClient.setServers=function(a){if(this.hf)throw"Error: setServers() - already connected; use this method before connect()";this.ab("setServers",a,"string",1,/^(\d+)?\s*https?:\/\/(\w|-)+(\.(\w|-)+)*(:\d+)?$/i,"Error: setServers() - invalid argument; expected a list of URLs");for(var b=[],c=0;c<a.length;c++){var d=/https?:\/\/(\w|-)+(\.(\w|-)+)*(:\d+)?$/i.exec(a[c])[0],e=/^\d+/.exec(a[c]);if(e===null)e=100;else{e=parseInt(e[0]);if(e>100)throw"Error: setServers() - invalid weight; expected a number between 0 and 100";
}this.di||this.dj(d);b.push({m:d,d4:e})}this.bj=b;this.bn.bo=[];for(c=0;c<a.length;c++){this.bn.bo[c]={};this.bn.bo[c].bp=0;this.bn.bo[c].d0=0;this.bn.bo[c].bs=0;this.bn.bo[c].cv=0;this.bn.bo[c].cc=0;this.bn.bo[c].b1={}}};MigratoryDataClient.getSubjects=function(){return this.a7(this.hg)};
MigratoryDataClient.setMessageHandler=function(a){if(this.hf)throw"Error: setMessageHandler() - already connected; use this method before connect()";if(typeof a!=="function")throw"Error: setMessageHandler() - invalid argument; expected a function";this.cl=a};
MigratoryDataClient.setStatusHandler=function(a){if(this.hf)throw"Error: setStatusHandler() - already connected; use this method before connect()";if(typeof a!=="function")throw"Error: setStatusHandler() - invalid argument; expected a function";this.d=a};MigratoryDataClient.setLogHandler=function(a){if(typeof a!=="function")throw"Error: setLogHandler() - invalid argument; expected a function";this.c5=a};MigratoryDataClient.subscribe=function(a){MigratoryDataClient.subscribeWithHistory(a,0)};
MigratoryDataClient.subscribeWithHistory=function(a,b){this.ac("subscribeWithHistory",a,"string",1,"Error: subscribe() - invalid first argument; expected a list of valid topics");if(typeof b!=="number"||b<0)throw"Error: subscribeWithHistory() - invalid second argument; expected an integer higher or equal to 0";a=this.a8(a,this.hg);if(a.length!==0){for(var c=0;c<a.length;c++)this.hh[a[c]]=b;this.hg=this.aa(this.hg,a);if(this.hf){b={};b.ap=this.as;b.cj=a;b.ef=this.a0(this.hh,a);b.ee=true;this.cz(b)}}};
MigratoryDataClient.unsubscribe=function(a){this.ac("unsubscribe",a,"string",1,"Error: unsubscribe() - invalid argument; expected a list of valid topics");a=this.a9(a,this.hg);if(a.length!==0){for(var b=0;b<a.length;b++)delete this.hh[a[b]];this.hg=this.a8(this.hg,a);if(this.hf){b={};b.ap=this.au;b.cj=a;this.cz(b)}}};MigratoryDataClient.disconnect=function(){if(this.hf){this.hf=false;this.b(false)&&this.f0()}};
MigratoryDataClient.setEntitlementToken=function(a){if(this.hf)throw"Error: setEntitlementToken() - already connected; use this method before connect()";this.e8=a};
MigratoryDataClient.setNumberOfSubdomainLevels=function(a){if(this.hf)throw"Error: setNumberOfSubdomainLevels() - already connected; use this method before connect()";if(this.bj.length>0)throw"Error: setNumberOfSubdomainLevels() - unable to set the number of subdomain levels when servers are already configured; use this method before setServers()";if(typeof a!=="number"||a<2)throw"Error: setNumberOfSubdomainLevels() - invalid argument; expected an integer higher or equal to 2";this.n=a};
MigratoryDataClient.getInfo=function(){if(!this.hf)throw"Error: getInfo() - not connected; use this method after connect()";s="Date: "+(new Date).toString()+"\n";s+="Uptime: "+((new Date).getTime()-this.bn.hi)+" ms\n";s+="window.location: "+window.location+"\n";s+="document.domain: "+document.domain+"\n";s+="User-agent: "+navigator.userAgent+"\n";s+="Detected browser: "+this.c+"\n";s+="Servers: ";for(var a=0;a<this.bj.length;a++){if(a>0)s+=", ";s+=this.bj[a].d4+" "+this.bj[a].m}s+="\nSubjects: "+
this.cj.toString()+"\n";s+="Connection status ["+(this.bk===null?null:this.bj[this.bk].m)+"]: "+this.b2+"\n";s+="Time from last server activity: "+(this.bn.cu!==null?(new Date).getTime()-this.bn.cu:null)+" ms\n";s+="Servers down before notify: "+this.db+"\n";s+="Consecutive server down count: "+this.be+" times\n";for(a=0;a<this.bn.bo.length;a++){s+="\nServer up ["+this.bj[a].m+"]: "+this.bn.bo[a].bp+" times\n";s+="Server down ["+this.bj[a].m+"]: "+this.bn.bo[a].d0+" times\n";s+="Server connection recycled ["+
this.bj[a].m+"]: "+this.bn.bo[a].bs+" times\n";s+="Received server events ["+this.bj[a].m+"]: "+this.bn.bo[a].cv+"\n";s+="Received messages ["+this.bj[a].m+"]: "+this.bn.bo[a].cc+"\n";for(var b in this.bn.bo[a].b1)if(this.bn.bo[a].b1.hasOwnProperty(b))s+="Error ["+this.bj[a].m+"] x"+this.bn.bo[a].b1[b]+" times : "+b+"\n"}return s};
MigratoryDataClient.publish=function(a){if(!this.hf)throw"Error: publish() - not connected; use this method after connect()";if(a===undefined||a===null)throw"Error: publish() - invalid argument; expected a valid message";if(a.subject===undefined||a.subject===null)throw"Error: publish() - invalid argument; expected a valid message with a non-empty topic";this.ac("publish",[a.subject],"string",1,"Error: publish() - invalid argument; expected a valid message,  "+a.subject+" is the cause of the error");
if(a.content===undefined||a.content===null)throw"Error: publish() - invalid argument; expected a valid message with a non-empty content";a.replySubject!==undefined&&a.replySubject!==null&&MigratoryDataClient.subscribe([a.replySubject]);var b={};b.ap=this.aw;b.em=a;this.cz(b)};
MigratoryDataClient.setQuickReconnectMaxRetries=function(a){if(this.hf)throw"Error: setQuickReconnectMaxRetries() - already connected; use this method before connect()";if(typeof a!=="number"||a<2)throw"Error: setQuickReconnectMaxRetries() - invalid argument; expected an integer higher or equal to 2";this.v=a};
MigratoryDataClient.setQuickReconnectInitialDelay=function(a){if(this.hf)throw"Error: setQuickReconnectInitialDelay() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: setQuickReconnectInitialDelay() - invalid argument; expected an integer higher or equal to 1";this.w=a*1E3};
MigratoryDataClient.setReconnectPolicy=function(a){if(this.hf)throw"Error: setReconnectPolicy()  - already connected; use this method before connect()";if(a===undefined||a!==MigratoryDataClient.CONSTANT_WINDOW_BACKOFF&&a!==MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF)throw"Error: setReconnectPolicy() - invalid argument; expected CONSTANT_WINDOW_BACKOFF or TRUNCATED_EXPONENTIAL_BACKOFF";this.x=a};
MigratoryDataClient.setReconnectTimeInterval=function(a){if(this.hf)throw"Error: setReconnectTimeInterval() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: setReconnectTimeInterval() - invalid argument; expected an integer higher or equal to 1";this.y=a*1E3};
MigratoryDataClient.setReconnectMaxDelay=function(a){if(this.hf)throw"Error: setReconnectMaxDelay() - already connected; use this method before connect()";if(typeof a!=="number"||a<1)throw"Error: setReconnectMaxDelay() - invalid argument; expected an integer higher or equal to 1";this.z=a*1E3};
MigratoryDataClient.notifyWhenReconnectRateExceedsThreshold=function(a){if(this.hf)throw"Error: notifyWhenReconnectRateExceedsThreshold() - already connected; use this method before connect()";if(typeof a!=="number"||a<2)throw"Error: notifyWhenReconnectRateExceedsThreshold() - invalid argument; expected an integer higher or equal to 2";this.d3=a};
MigratoryDataClient.pause=function(){if(!this.hf)throw"Error: pause() - not connected; use this method after connect()";if(MigratoryDataClient.hj!=false){MigratoryDataClient.hj=false;var a={};a.ap=this.es;this.cz(a)}};MigratoryDataClient.resume=function(){if(!this.hf)throw"Error: resume() - not connected; use this method after connect()";if(MigratoryDataClient.hj!=true){MigratoryDataClient.hj=true;var a={};a.ap=this.et;this.cz(a)}};
if(!Number.MAX_SAFE_INTEGER)Number.MAX_SAFE_INTEGER=Math.pow(2,53)-1;MigratoryDataClient.e9=6;MigratoryDataClient.di=false;MigratoryDataClient.dl=false;MigratoryDataClient.dr=false;MigratoryDataClient.cy=9E5;MigratoryDataClient.hk=3E4+Math.floor(Math.random()*1E4);MigratoryDataClient.bb=MigratoryDataClient.hk;MigratoryDataClient.u=1E4;MigratoryDataClient.fr=100;MigratoryDataClient.fm=524288;MigratoryDataClient.db=1;MigratoryDataClient.d3=10;MigratoryDataClient.n=0;MigratoryDataClient.b7=false;
MigratoryDataClient.gk=2;MigratoryDataClient.v=3;MigratoryDataClient.w=5E3;MigratoryDataClient.x=MigratoryDataClient.TRUNCATED_EXPONENTIAL_BACKOFF;MigratoryDataClient.y=2E4;MigratoryDataClient.z=36E4;MigratoryDataClient.e8=null;MigratoryDataClient.cs=null;MigratoryDataClient.hj=true;MigratoryDataClient.as="SUBSCRIBE";MigratoryDataClient.au="UNSUBSCRIBE";MigratoryDataClient.an="PING";MigratoryDataClient.aq="CONNECT";MigratoryDataClient.aw="PUBLISH";MigratoryDataClient.es="PAUSE";
MigratoryDataClient.et="RESUME";MigratoryDataClient.hl=0;MigratoryDataClient.dy=1;MigratoryDataClient.e3=2;MigratoryDataClient.dm=3;MigratoryDataClient.hm=4;MigratoryDataClient.e4=5;MigratoryDataClient.hn=6;MigratoryDataClient.ho=7;MigratoryDataClient.dq=8;MigratoryDataClient.dw=9;MigratoryDataClient.du=10;MigratoryDataClient.b3="SERVER_UP";MigratoryDataClient.d9="SERVER_DOWN";MigratoryDataClient.bm="SERVER_RECYCLE";MigratoryDataClient.ce=0;MigratoryDataClient.gl=1;MigratoryDataClient.c2="1";
MigratoryDataClient.hp="2";MigratoryDataClient.c3="3";MigratoryDataClient.c4="4";MigratoryDataClient.e6=1;MigratoryDataClient.eb="ERROR_TIMEOUT";MigratoryDataClient.hq="ERROR_HTTP";MigratoryDataClient.az="ERROR_SERVER";MigratoryDataClient.cg="SUBSCRIBE_TYPE_NORMAL";MigratoryDataClient.gi="SUBSCRIBE_TYPE_HISTORY";MigratoryDataClient.cf="SUBSCRIBE_TYPE_RECOVERY";MigratoryDataClient.cp="cache_ok";MigratoryDataClient.cr="cache_ok_no_new_message";MigratoryDataClient.cq="cache_ok_new_epoch";
MigratoryDataClient.hr="no_cache";MigratoryDataClient.hs="no_seq";MigratoryDataClient.co="end";MigratoryDataClient.ht=0;MigratoryDataClient.hu=1;MigratoryDataClient.ci=2;MigratoryDataClient.c=MigratoryDataClient.a();MigratoryDataClient.e0=null;MigratoryDataClient.bj=[];MigratoryDataClient.cl=null;MigratoryDataClient.d=null;MigratoryDataClient.ck=[];MigratoryDataClient.b9=Number.MAX_SAFE_INTEGER;MigratoryDataClient.d2=0;MigratoryDataClient.d1=(new Date).getTime();MigratoryDataClient.er=false;
MigratoryDataClient.j=[];MigratoryDataClient.h=false;MigratoryDataClient.bk=null;MigratoryDataClient.b2=null;MigratoryDataClient.hg=[];MigratoryDataClient.hh={};MigratoryDataClient.cj=[];MigratoryDataClient.c1={};MigratoryDataClient.b5=null;MigratoryDataClient.bc=null;MigratoryDataClient.ew=null;MigratoryDataClient.cx=(new Date).getTime();MigratoryDataClient.cw=null;MigratoryDataClient.da=[];MigratoryDataClient.be=0;MigratoryDataClient.bf=0;MigratoryDataClient.bq=false;MigratoryDataClient.dd=null;
MigratoryDataClient.eo=[];MigratoryDataClient.ao=null;MigratoryDataClient.ev=null;MigratoryDataClient.ea=null;MigratoryDataClient.d5=null;MigratoryDataClient.bn={};MigratoryDataClient.bn.hi=(new Date).getTime();MigratoryDataClient.bn.cu=null;MigratoryDataClient.bn.bo=[];MigratoryDataClient.dh=false;MigratoryDataClient.dv=false;MigratoryDataClient.hf=false;MigratoryDataClient.c5=function(a){window.console&&console.log(a)};
if(window.WebSocket)MigratoryDataClient.dh=true;else if(window.MozWebSocket)MigratoryDataClient.dh=true;if(typeof MigratoryDataClient_Disable_WebSocket_Transport!=="undefined"&&MigratoryDataClient_Disable_WebSocket_Transport==true)MigratoryDataClient.dh=false;
if(MigratoryDataClient.dh==false)if(window.XDomainRequest){var xdrTest=new XDomainRequest;try{xdrTest.open("GET",window.location.protocol+"//127.0.0.1");xdrTest.send();MigratoryDataClient.dv=true;xdrTest.abort()}catch(e$$7){xdrTest.abort();MigratoryDataClient.dv=false}}else MigratoryDataClient.dv=false;
if(MigratoryDataClient.c==="IE")try{window.attachEvent("onunload",function(){MigratoryDataClient.f0()})}catch(e$$8){window.addEventListener("unload",function(){MigratoryDataClient.f0()},false)}else window.addEventListener("unload",function(){MigratoryDataClient.f0()},false);MigratoryDataClient.e();if(MigratoryDataClient.c==="WebKit iPhone")MigratoryDataClient.fm=65536;else if(MigratoryDataClient.c==="Opera Mobile"){MigratoryDataClient.fm=32768;MigratoryDataClient.fr=500}
if(MigratoryDataClient.dh==true){MigratoryDataClient.di=true;MigratoryDataClient.dl=true;MigratoryDataClient.dr=true}else if(MigratoryDataClient.dv&&window.postMessage){MigratoryDataClient.di=true;MigratoryDataClient.dl=true;MigratoryDataClient.dr=true;try{window.attachEvent("onmessage",MigratoryDataClient.fn)}catch(e$$9){window.addEventListener("onmessage",MigratoryDataClient.fn,false)}}else if(XMLHttpRequest&&(new XMLHttpRequest).withCredentials!==undefined){MigratoryDataClient.di=true;MigratoryDataClient.dl=
true}else if(swfobject&&swfobject.hasFlashPlayerVersion("9")&&(typeof MigratoryDataClient_Allow_Flash_Transport==="undefined"||MigratoryDataClient_Allow_Flash_Transport==true)){MigratoryDataClient.di=true;MigratoryDataClient.i(function(){MigratoryDataClient.fi()})}if(!MigratoryDataClient.di||MigratoryDataClient.dl)MigratoryDataClient.i(function(){MigratoryDataClient.eu()});
